// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTnBDqAjvx-t7hTX263e9J548o_z0Fyvg',
    appId: '1:728855954649:web:76cc7e4cb99e01a1f12ac8',
    messagingSenderId: '728855954649',
    projectId: 'survey-web-54101',
    authDomain: 'survey-web-54101.firebaseapp.com',
    storageBucket: 'survey-web-54101.appspot.com',
    measurementId: 'G-TX4ZVCDTS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0upfHkB2HXTWOSrLkIbl3bTzfUz8ONM4',
    appId: '1:728855954649:android:d497b696122701d5f12ac8',
    messagingSenderId: '728855954649',
    projectId: 'survey-web-54101',
    storageBucket: 'survey-web-54101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbAZJKV993wctnNw23EINRcVmAzAqfdM',
    appId: '1:728855954649:ios:780230e709dd4ba1f12ac8',
    messagingSenderId: '728855954649',
    projectId: 'survey-web-54101',
    storageBucket: 'survey-web-54101.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbAZJKV993wctnNw23EINRcVmAzAqfdM',
    appId: '1:728855954649:ios:3137e74efd309323f12ac8',
    messagingSenderId: '728855954649',
    projectId: 'survey-web-54101',
    storageBucket: 'survey-web-54101.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
